#!/bin/bash

# ! /bin/bash        #denote which shell is interpreting the line

#                     denotes comments
#echo boy             print the output to screen


echo "Hello to you\!"  #print output to screen    

set variable_name = "value"  #local variable
set name = "sudeep"

set env VARIABLE_NAME value  #global/environmental variable
set env PRINTER Shakespeare

echo $argv[1] $argv[2] $argv[3] #argument using array
echo $argv[*]
echo $#argv                     #display no. of argument

n = 5 + 5
echo $n






